### ISSUE TITLE
Having trouble running example on MacOS

### ISSUE THREAD

**Issue by seandoyle** [nivwusquorum/tensorflow-deepq#1]
Hi -

I've installed TensorFlow and I can run their examples. I suspect I'm missing a path or an initialization step.

This is my version of Python:
Python 2.7.10 :: Anaconda 2.4.0 (x86_64)

When I invoke your sample command it throws an error on the first line. I get similar import problems when I use Jupyter to open the Karpathy notebook:

python tf_rl/controller/human_controller.py
Traceback (most recent call last):
  File "tf_rl/controller/human_controller.py", line 1, in <module>
    from tf_rl.utils.getch import getch
  File "/Users/mesozoic/Documents/MachineLearning/google/tensorflow-deepq/tf_rl/**init**.py", line 1, in <module>
    from .simulate import simulate
  File "/Users/mesozoic/Documents/MachineLearning/google/tensorflow-deepq/tf_rl/simulate.py", line 7, in <module>
    from tf_rl.utils.event_queue import EventQueue
  File "/Users/mesozoic/Documents/MachineLearning/google/tensorflow-deepq/tf_rl/utils/event_queue.py", line 3, in <module>
    from queue import PriorityQueue
ImportError: No module named queue

Thanks!

**Comment by siemanko** [comment]
You need to install python module "future"

**Comment by seandoyle** [comment]
I also had to install pyecuclid and make one code change in the karpathy_game.ipynb:
-    "             actions_per_game_second=10,\n",
-    "             actions_per_simulation_second=10,\n",

After this the notebook loaded just fine in jupyter. I'm sorry I can't give real feedback yet - I'm still climbing the python learning curve. Thanks!

**Comment by siemanko** [comment]
Thanks a lot for pointing that out! It is fixed now.
