### ISSUE TITLE
undefined symbol: PyClass_Type

### ISSUE THREAD

**Issue by andyyuan78** [nivwusquorum/tensorflow-deepq#13]
envy@ub1404:~/os_pri/github/tensorflow-deepq$ PYTHONPATH=~/os_pri/github/tensorflow-deepq:/home/envy/os_pri/github/tensorflow/_python_build:$PYTHONPATH python3 tf_rl/controller/human_controller.py
Traceback (most recent call last):
  File "tf_rl/controller/human_controller.py", line 1, in <module>
    from tf_rl.utils.getch import getch
  File "/home/envy/os_pri/github/tensorflow-deepq/tf_rl/utils/__init__.py", line 1, in <module>
    import tensorflow as tf
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow import contrib
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/contrib/__init__.py", line 23, in <module>
    from tensorflow.contrib import layers
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/contrib/layers/__init__.py", line 67, in <module>
    from tensorflow.contrib.layers.python.framework.tensor_util import *
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/contrib/layers/python/framework/tensor_util.py", line 21, in <module>
    from tensorflow.python.framework.ops import Tensor
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/framework/ops.py", line 39, in <module>
    from tensorflow.python.framework import versions
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/framework/versions.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /home/envy/os_pri/github/tensorflow/_python_build/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyClass_Type
envy@ub1404:~/os_pri/github/tensorflow-deepq$ 
envy@ub1404:~/os_pri/github/tensorflow-deepq$

**Comment by siemanko** [comment]
Hi Andy,

I believe your python installation is broken.

Try:

``` bash
sudo apt-get install python3
```

Good luck!

**Comment by andyyuan78** [comment]
no, my python3 is well

but I do have both py2 and py3  installed, i guess that's the issue

**Comment by andyyuan78** [comment]
should we reopen this case?
it seems someone other report on tensorflow  that py3.4 doesn't works well with it

**Comment by siemanko** [comment]
But you are getting link errors, while my project is pure python. It is
almost certainly nothing to do with my project.

**Comment by siemanko** [comment]
I would recomment superuser or stackoverflow, to solve your problem.
